export const OTHER_CITY_VALUE = "OTRO";

export const argentinaCityOptions = [
  { value: "Villa Constitucion, Santa Fe", label: "Villa Constitucion, Santa Fe" },
  { value: "Empalme Villa Constitucion, Santa Fe", label: "Empalme Villa Constitucion, Santa Fe" },
  { value: "Pavon, Santa Fe", label: "Pavon, Santa Fe" },
  { value: "Pavon Arriba, Santa Fe", label: "Pavon Arriba, Santa Fe" },
  { value: "Theobald, Santa Fe", label: "Theobald, Santa Fe" },
  { value: "Arroyo Seco, Santa Fe", label: "Arroyo Seco, Santa Fe" },
  { value: "Fighiera, Santa Fe", label: "Fighiera, Santa Fe" },
  { value: "General Lagos, Santa Fe", label: "General Lagos, Santa Fe" },
  { value: "Alvear, Santa Fe", label: "Alvear, Santa Fe" },
  { value: "Pueblo Esther, Santa Fe", label: "Pueblo Esther, Santa Fe" },
  { value: "Villa Gobernador Galvez, Santa Fe", label: "Villa Gobernador Galvez, Santa Fe" },
  { value: "Rosario, Santa Fe", label: "Rosario, Santa Fe" },
  { value: "Perez, Santa Fe", label: "Perez, Santa Fe" },
  { value: "Soldini, Santa Fe", label: "Soldini, Santa Fe" },
  { value: "Funes, Santa Fe", label: "Funes, Santa Fe" },
  { value: "Roldan, Santa Fe", label: "Roldan, Santa Fe" },
  { value: "Granadero Baigorria, Santa Fe", label: "Granadero Baigorria, Santa Fe" },
  { value: "Capitan Bermudez, Santa Fe", label: "Capitan Bermudez, Santa Fe" },
  { value: "Fray Luis Beltran, Santa Fe", label: "Fray Luis Beltran, Santa Fe" },
  { value: "San Lorenzo, Santa Fe", label: "San Lorenzo, Santa Fe" },
  { value: "Puerto General San Martin, Santa Fe", label: "Puerto General San Martin, Santa Fe" },
  { value: "Timbues, Santa Fe", label: "Timbues, Santa Fe" },
  { value: "Carcarana, Santa Fe", label: "Carcarana, Santa Fe" },
  { value: "Casilda, Santa Fe", label: "Casilda, Santa Fe" },
  { value: "Arequito, Santa Fe", label: "Arequito, Santa Fe" },
  { value: "Chabas, Santa Fe", label: "Chabas, Santa Fe" },
  { value: "Firmat, Santa Fe", label: "Firmat, Santa Fe" },
  { value: "Melincue, Santa Fe", label: "Melincue, Santa Fe" },
  { value: "Venado Tuerto, Santa Fe", label: "Venado Tuerto, Santa Fe" },
  { value: "Canada de Gomez, Santa Fe", label: "Canada de Gomez, Santa Fe" },
  { value: "Armstrong, Santa Fe", label: "Armstrong, Santa Fe" },
  { value: "Las Parejas, Santa Fe", label: "Las Parejas, Santa Fe" },
  { value: "Alcorta, Santa Fe", label: "Alcorta, Santa Fe" },
  { value: "Maximo Paz, Santa Fe", label: "Maximo Paz, Santa Fe" },
  { value: "Bombal, Santa Fe", label: "Bombal, Santa Fe" },
  { value: "Hughes, Santa Fe", label: "Hughes, Santa Fe" },
  { value: "Wheelwright, Santa Fe", label: "Wheelwright, Santa Fe" },
  { value: "Peyrano, Santa Fe", label: "Peyrano, Santa Fe" },
  { value: "Santa Teresa, Santa Fe", label: "Santa Teresa, Santa Fe" },
  { value: "San Nicolas de los Arroyos, Buenos Aires", label: "San Nicolas de los Arroyos, Buenos Aires" },
  { value: "Ramallo, Buenos Aires", label: "Ramallo, Buenos Aires" },
  { value: "Villa Ramallo, Buenos Aires", label: "Villa Ramallo, Buenos Aires" },
  { value: "Pergamino, Buenos Aires", label: "Pergamino, Buenos Aires" },
  { value: "Rojas, Buenos Aires", label: "Rojas, Buenos Aires" },
  { value: "Arrecifes, Buenos Aires", label: "Arrecifes, Buenos Aires" },
  { value: "Colon, Buenos Aires", label: "Colon, Buenos Aires" },
  { value: "Salto, Buenos Aires", label: "Salto, Buenos Aires" },
  { value: "San Pedro, Buenos Aires", label: "San Pedro, Buenos Aires" },
  { value: "Baradero, Buenos Aires", label: "Baradero, Buenos Aires" },
  { value: "San Antonio de Areco, Buenos Aires", label: "San Antonio de Areco, Buenos Aires" },
  { value: "Zarate, Buenos Aires", label: "Zarate, Buenos Aires" },
  { value: "Campana, Buenos Aires", label: "Campana, Buenos Aires" },
  { value: "Victoria, Entre Rios", label: "Victoria, Entre Rios" },
  { value: "Gualeguay, Entre Rios", label: "Gualeguay, Entre Rios" },
  { value: "Nogoya, Entre Rios", label: "Nogoya, Entre Rios" },
  { value: "Diamante, Entre Rios", label: "Diamante, Entre Rios" },
  { value: "CABA, Ciudad Autonoma de Buenos Aires", label: "CABA, Ciudad Autonoma de Buenos Aires" },
  { value: "La Plata, Buenos Aires", label: "La Plata, Buenos Aires" },
  { value: "Mar del Plata, Buenos Aires", label: "Mar del Plata, Buenos Aires" },
  { value: "Bahia Blanca, Buenos Aires", label: "Bahia Blanca, Buenos Aires" },
  { value: "Tandil, Buenos Aires", label: "Tandil, Buenos Aires" },
  { value: "Cordoba, Cordoba", label: "Cordoba, Cordoba" },
  { value: "Villa Carlos Paz, Cordoba", label: "Villa Carlos Paz, Cordoba" },
  { value: "Rio Cuarto, Cordoba", label: "Rio Cuarto, Cordoba" },
  { value: "Santa Fe, Santa Fe", label: "Santa Fe, Santa Fe" },
  { value: "Rafaela, Santa Fe", label: "Rafaela, Santa Fe" },
  { value: "Mendoza, Mendoza", label: "Mendoza, Mendoza" },
  { value: "San Rafael, Mendoza", label: "San Rafael, Mendoza" },
  { value: "San Miguel de Tucuman, Tucuman", label: "San Miguel de Tucuman, Tucuman" },
  { value: "Salta, Salta", label: "Salta, Salta" },
  { value: "San Salvador de Jujuy, Jujuy", label: "San Salvador de Jujuy, Jujuy" },
  { value: "Parana, Entre Rios", label: "Parana, Entre Rios" },
  { value: "Concordia, Entre Rios", label: "Concordia, Entre Rios" },
  { value: "Corrientes, Corrientes", label: "Corrientes, Corrientes" },
  { value: "Resistencia, Chaco", label: "Resistencia, Chaco" },
  { value: "Posadas, Misiones", label: "Posadas, Misiones" },
  { value: "Formosa, Formosa", label: "Formosa, Formosa" },
  { value: "Santiago del Estero, Santiago del Estero", label: "Santiago del Estero, Santiago del Estero" },
  { value: "San Fernando del Valle de Catamarca, Catamarca", label: "San Fernando del Valle de Catamarca, Catamarca" },
  { value: "La Rioja, La Rioja", label: "La Rioja, La Rioja" },
  { value: "San Juan, San Juan", label: "San Juan, San Juan" },
  { value: "San Luis, San Luis", label: "San Luis, San Luis" },
  { value: "Neuquen, Neuquen", label: "Neuquen, Neuquen" },
  { value: "Santa Rosa, La Pampa", label: "Santa Rosa, La Pampa" },
  { value: "Viedma, Rio Negro", label: "Viedma, Rio Negro" },
  { value: "Bariloche, Rio Negro", label: "Bariloche, Rio Negro" },
  { value: "Rawson, Chubut", label: "Rawson, Chubut" },
  { value: "Comodoro Rivadavia, Chubut", label: "Comodoro Rivadavia, Chubut" },
  { value: "Rio Gallegos, Santa Cruz", label: "Rio Gallegos, Santa Cruz" },
  { value: "Ushuaia, Tierra del Fuego", label: "Ushuaia, Tierra del Fuego" },
  { value: OTHER_CITY_VALUE, label: "Otro" }
] as const;

export const argentinaCityValues: string[] = argentinaCityOptions.map((city) => city.value);
